FORMAT: 1A
HOST: http://taxibye.oddesign.expert/api/v1/

# TaxiBye

TaxiBye 是一個可以記錄計程車行車路徑，並給予評價紀錄的 APP。使用者可以在告訴應用程式所搭計程車的車牌之後，開始記錄行車資料，並在結束時給予此計程車一個評分。

----

Change Log:

  - 2017.01.25 - 新增基本 API
  - 2017.02.02 - 新增 Authorization

----

# Group Authorization

## 登入 [/login]

使用 Email 和 Password 驗證使用者身份，並發行 Token

### Login [POST]

+ Request (application/json)

    + Attributes
      + data (Email Login Info)

+ Response 202 (application/json)

    + Attributes
      + data (Login Success Response)
      + errors (array)
      + meta (object)





# Group Taxis

## 積分排行 [/taxis/ranking{?number}]

列出計程車的積分排行。可指定數量上限。

### fetch ranking list [GET]

+ Parameters
    + number: 5 (string, optional) - 限制回傳的數量上限
      如果沒給值的話預設會回傳 10 筆資料
      + Default: `10`

+ Response 200 (application/json)

    + Attributes
      + data (array[Taxi Info])
      + errors (array)
      + meta (object)



## 車牌查詢 [/taxis/{license_plate_number}/query]

透過車牌查詢計程車的基本資料。

### query taxi by license plate number [POST]

+ Response 200 (application/json)

    + Attributes
      + data (Taxi Info)
      + errors (array)
      + meta (object)



## 行程紀錄 [/taxis/{license_plate_number}/trips]

### create a trip record [POST]

+ Request (application/json)

    + Headers

            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjF9.d8nHlCSuxGZJhvxktOd9beAW0YBsB6PNcTtr-M36XoE
            DeviceID: 15a6bf35-a455-4108-87d4-b669eb76ea58

    + Attributes
      + data (Trip Info)

+ Response 201 (application/json)

    + Attributes
      + data (Trip Created Response)
      + errors (array)
      + meta (object)


## Data Structures

### Email Login Info
+ email: `test@pricetagapp.com` (string, required) - 使用者 Email
+ password: `09sad8f9lk12` (string, required) - 使用者密碼

### Trip Info
+ startedAt: `1486364960` (number, required) - 行程開始時間
+ endedAt: `1486367282` (number, required) - 行程結束時間
+ route: `kasjdkljsadkljaskdj` (string, required) - 航跡檔（GPX）
+ ratingAttributes (Rating Request Data) - 評價內容

### Trip Created Response
+ taxi (Taxi Info)
+ trip (Trip Info)

### Rating Request Data
+ score: `4` (number, required) - 評分，請給整數
+ message: `最快最趴最大` (string, optional) - 留言
+ tripFeelingId: `1` (number, required) - 行程感受選項

### Login Success Response
+ authToken: `eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjF9.d8nHlCSuxGZJhvxktOd9beAW0YBsB6PNcTtr-M36XoE` (string, required) - JWT


###Taxi Ranking List
+ taxis (array[Taxi Info])

### Taxi Info
+ id: `7788-KM` (string, required) - PK
+ type: `taxis` (string, required) - resource type
+ attributes (object, required)
  + plateNumber: `7788-KM` (string, required) - 車牌號碼
  + driver: `木村` (string, optional) - 駕駛人
  + avgRating: `1.8` (number, required) - 平均評分
  + updatedAt: `1486367282` (number, required) - 更新時間